name: Build Docker Image
on:
  push:
    branches: ['**']
    tags: ['*.*.*']
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract git context
        id: git
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=tag;]$(git tag -l --points-at HEAD)"
      - name: Login to GitHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the image
        run: docker build -t mathrix/lumen-base:latest .
      - name: Push the image
        run: docker push mathrix/lumen-base:latest
      - name: Add tag if necessary
        if: contains(steps.git.outputs.tag, '.')
        run: |
          docker tag mathrix/lumen-base:${{ steps.git.outputs.tag }} mathrix/lumen-base:latest
          docker push mathrix/lumen-base:${{ steps.git.outputs.tag }}

