name: Build Docker Image
on:
  push:
    branches: ['*'] # Do not run on tags
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: docker login docker.pkg.github.com -u mathrix-education -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t docker.pkg.github.com/mathrix-education/docker-php-fpm-nginx/php-fpm-nginx:latest .
      - run: docker push docker.pkg.github.com/mathrix-education/docker-php-fpm-nginx/php-fpm-nginx:latest

